// ─────────────────────────────────────────────────────────────────────────────
// Seed / representative data — used when Supabase is not yet configured.
// Replace the `getMetrics()` fetch in app/page.tsx with real Supabase queries
// once your project URL and anon key are in .env.local.
// ─────────────────────────────────────────────────────────────────────────────

import type { Estimation, AuditEvent, ReviewComment } from '@/types'

export const SEED_ESTIMATION: Estimation = {
  id: 'seed-est-001',
  project_id: 'seed-proj-001',
  version_label: 'V1.0.4-EST',
  status: 'committed',
  duration_weeks: 61,          // ~14 months
  start_date: '2024-11-01',
  baseline_cost: 4_300_000,
  created_by: 'seed-user-001',
  created_at: '2024-10-23T09:15:00Z',
  updated_at: '2024-10-24T14:32:00Z',
  workstreams: [
    {
      id: 'ws-1',
      estimation_id: 'seed-est-001',
      name: 'Cloud Infrastructure',
      sort_order: 1,
      resources: [
        // 6 consultants × $185/hr × 40h × 61 weeks × 95% util ≈ $2.7M → scaled to budget cap
        ...Array.from({ length: 6 }, (_, i) => ({
          id: `ws1-r${i}`,
          workstream_id: 'ws-1',
          rate_card_id: 'rc-consultant-onshore',
          display_name: `Cloud Engineer #${i + 1}`,
          resource_type: 'consultant' as const,
          location_tier: i < 2 ? 'onshore' as const : 'offshore' as const,
          weekly_hours: 40,
          utilization_pct: 95,
          start_week: 0,
          end_week: 60,
          hourly_rate: i < 2 ? 185 : 95,
          role_title: 'Cloud Infrastructure Engineer',
        })),
      ],
    },
    {
      id: 'ws-2',
      estimation_id: 'seed-est-001',
      name: 'Data Engineering',
      sort_order: 2,
      resources: Array.from({ length: 5 }, (_, i) => ({
        id: `ws2-r${i}`,
        workstream_id: 'ws-2',
        rate_card_id: 'rc-consultant-offshore',
        display_name: `Data Engineer #${i + 1}`,
        resource_type: 'consultant' as const,
        location_tier: 'offshore' as const,
        weekly_hours: 40,
        utilization_pct: 90,
        start_week: 4,
        end_week: 56,
        hourly_rate: 95,
        role_title: 'Data Engineer',
      })),
    },
    {
      id: 'ws-3',
      estimation_id: 'seed-est-001',
      name: 'UX/UI Modernization',
      sort_order: 3,
      resources: Array.from({ length: 3 }, (_, i) => ({
        id: `ws3-r${i}`,
        workstream_id: 'ws-3',
        rate_card_id: 'rc-ft-onshore',
        display_name: `UX Designer #${i + 1}`,
        resource_type: 'full_time' as const,
        location_tier: 'onshore' as const,
        weekly_hours: 40,
        utilization_pct: 80,
        start_week: 8,
        end_week: 48,
        hourly_rate: 152,
        role_title: 'UX Designer',
      })),
    },
    {
      id: 'ws-4',
      estimation_id: 'seed-est-001',
      name: 'DevOps & CI/CD',
      sort_order: 4,
      resources: Array.from({ length: 4 }, (_, i) => ({
        id: `ws4-r${i}`,
        workstream_id: 'ws-4',
        rate_card_id: 'rc-consultant-onshore',
        display_name: `DevOps Engineer #${i + 1}`,
        resource_type: i < 2 ? 'consultant' as const : 'full_time' as const,
        location_tier: 'onshore' as const,
        weekly_hours: 40,
        utilization_pct: 90,
        start_week: 0,
        end_week: 60,
        hourly_rate: i < 2 ? 185 : 152,
        role_title: 'DevOps Engineer',
      })),
    },
    {
      id: 'ws-5',
      estimation_id: 'seed-est-001',
      name: 'Security & Compliance',
      sort_order: 5,
      resources: Array.from({ length: 3 }, (_, i) => ({
        id: `ws5-r${i}`,
        workstream_id: 'ws-5',
        rate_card_id: 'rc-consultant-offshore',
        display_name: `Security Analyst #${i + 1}`,
        resource_type: 'consultant' as const,
        location_tier: i === 0 ? 'onshore' as const : 'offshore' as const,
        weekly_hours: 40,
        utilization_pct: 85,
        start_week: 12,
        end_week: 60,
        hourly_rate: i === 0 ? 185 : 95,
        role_title: 'Security Analyst',
      })),
    },
  ],
  geo_locations: [
    {
      id: 'geo-1',
      estimation_id: 'seed-est-001',
      location_name: 'United States (HQ)',
      location_tier: 'onshore',
      percentage: 32,
      avg_hourly_rate: 185,
    },
    {
      id: 'geo-2',
      estimation_id: 'seed-est-001',
      location_name: 'United Kingdom',
      location_tier: 'onshore',
      percentage: 8,
      avg_hourly_rate: 170,
    },
    {
      id: 'geo-3',
      estimation_id: 'seed-est-001',
      location_name: 'India (Bangalore)',
      location_tier: 'offshore',
      percentage: 45,
      avg_hourly_rate: 85,
    },
    {
      id: 'geo-4',
      estimation_id: 'seed-est-001',
      location_name: 'Poland (Kraków)',
      location_tier: 'offshore',
      percentage: 15,
      avg_hourly_rate: 110,
    },
  ],
}

export const SEED_COMMENTS: ReviewComment[] = [
  {
    id: 'comment-1',
    estimation_id: 'seed-est-001',
    author_id: 'user-cio',
    author_name: 'J. Mitchell',
    author_role: 'CIO',
    body: 'Cloud infrastructure costs for Q3 seem aggressive. Can we explore multi-cloud redundancy options for Workstream A?',
    resolved: false,
    created_at: new Date(Date.now() - 3_600_000).toISOString(),
  },
  {
    id: 'comment-2',
    estimation_id: 'seed-est-001',
    author_id: 'user-sa',
    author_name: 'R. Patel',
    author_role: 'SA',
    body: 'Onshore/Offshore mix approved. Proceed with vendor rate renegotiations as planned.',
    resolved: true,
    created_at: new Date(Date.now() - 14_400_000).toISOString(),
  },
]

export const SEED_EVENTS: AuditEvent[] = [
  {
    id: 'evt-1',
    estimation_id: 'seed-est-001',
    event_kind: 'workstream_updated',
    actor_id: 'user-sa',
    actor_name: 'R. Patel',
    actor_role: 'Lead Architect',
    description: 'Updated "Workstream A" baseline with 3 additional Node.js specialists.',
    created_at: new Date(Date.now() - 5_400_000).toISOString(),
  },
  {
    id: 'evt-2',
    estimation_id: 'seed-est-001',
    event_kind: 'geo_mix_changed',
    actor_id: 'user-sa',
    actor_name: 'R. Patel',
    actor_role: 'Lead Architect',
    description: 'Offshore ratio adjusted from 55% to 60% following Steering approval.',
    created_at: new Date(Date.now() - 32_400_000).toISOString(),
  },
  {
    id: 'evt-3',
    estimation_id: 'seed-est-001',
    event_kind: 'estimation_updated',
    actor_id: 'user-sa',
    actor_name: 'R. Patel',
    actor_role: 'Lead Architect',
    description: 'Critical alert: Resource overallocation detected in scenario "Aggressive Modernization".',
    created_at: new Date(Date.now() - 61_200_000).toISOString(),
  },
  {
    id: 'evt-4',
    estimation_id: 'seed-est-001',
    event_kind: 'snapshot_committed',
    actor_id: 'user-sa',
    actor_name: 'R. Patel',
    actor_role: 'Lead Architect',
    description: 'New Estimation Snapshot "V1.0.4-EST" committed by lead architect.',
    created_at: '2024-10-23T09:15:00Z',
  },
]
